services:
  rdbms:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rdbms:/var/lib/postgresql/data
volumes:
  rdbms:
    driver: local