services:
  web:
    build: .
    container_name: web
    ports:
      - 8080:8080
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://rdbms/postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://rdbms/postgres
    depends_on:
      - rdbms
  rdbms:
    image: postgres:16-alpine
    container_name: rdbms
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rdbms:/var/lib/postgresql/data
      - ./init-rdb:/docker-entrypoint-initdb.d
volumes:
  rdbms:
    driver: local