services:
  rdbms:
    image: postgres:16-alpine
    container_name: rdbms
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rdbms:/var/lib/postgresql/data
      - ./init-rdb:/docker-entrypoint-initdb.d
volumes:
  rdbms:
    driver: local