---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lab21
  namespace: dev
spec:
  hosts:
    - "90.156.213.50"
  gateways:
    - lab21-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: lab21
            subset: v1
          weight: 70
        - destination:
            host: lab21
            subset: v2
          weight: 30